
REGISTERED      =       1

VOLUMERAMP      =       1
DOUBLEVOLUME    =       0
DITHEROUTPUT    =       1

USECLICKFADETHRESHHOLD= 0
CLICKFADETHRESHHOLD =   4096

RAMPSPEED       =       8
RAMPCOMPENSATE  =       255

CUBICINTERPOLATION      =       1
QUADRATICINTERPOLATION  =       0
LINEARINTERPOLATION     =       0
POINTSAMPLED            =       0

INTELOPTIMISED          =       0

FileID          DW      0

